add_lunch_combo solo_flo-user
add_lunch_combo solo_grouper-userdebug
add_lunch_combo solo_hammerhead-user
add_lunch_combo solo_mako-userdebug
add_lunch_combo solo_manta-userdebug
add_lunch_combo solo_shamu-user

