add_lunch_combo felix_flo-user
add_lunch_combo felix_grouper-userdebug
add_lunch_combo felix_hammerhead-user
add_lunch_combo felix_mako-userdebug
add_lunch_combo felix_manta-userdebug
add_lunch_combo felix_shamu-user

